# Generated by Django 2.1.3 on 2018-12-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='len1',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='len2',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='len3',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='x',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='y',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='z',
            field=models.IntegerField(default=10),
        ),
    ]
