# Generated by Django 2.1.3 on 2018-12-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20181206_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='x',
            new_name='cx',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='y',
            new_name='cy',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='fill',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='radius',
            new_name='r',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='len1',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='len2',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='len3',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='z',
        ),
    ]
