# Generated by Django 2.1.3 on 2019-02-20 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('command', models.CharField(max_length=10)),
                ('paramters', models.CharField(max_length=10)),
                ('alreadyExists', models.BooleanField()),
                ('argumentsProv', models.CharField(max_length=20)),
                ('isPiped', models.BooleanField()),
                ('userid', models.IntegerField()),
                ('isAlais', models.BooleanField()),
                ('orginal', models.CharField(max_length=10)),
                ('pastaComments', models.CharField(max_length=100)),
                ('isRoot', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerReply',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('replyText', models.CharField(max_length=100)),
                ('alreadyExists', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserShell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='commands',
            name='ServerReply',
            field=models.ManyToManyField(to='djangoendpoint.ServerReply'),
        ),
        migrations.AddField(
            model_name='commands',
            name='UserShell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoendpoint.UserShell'),
        ),
    ]
