# Generated by Django 2.1.3 on 2019-02-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoendpoint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commands',
            name='UserShell',
        ),
        migrations.AlterField(
            model_name='commands',
            name='ServerReply',
            field=models.ManyToManyField(blank=True, to='djangoendpoint.ServerReply'),
        ),
        migrations.AlterField(
            model_name='commands',
            name='alreadyExists',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commands',
            name='isAlais',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commands',
            name='isPiped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commands',
            name='isRoot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commands',
            name='orginal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='commands',
            name='pastaComments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='commands',
            name='userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serverreply',
            name='alreadyExists',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serverreply',
            name='replyText',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usershell',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='usershell',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='usershell',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usershell',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
