# Generated by Django 2.1.3 on 2019-02-20 19:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resthackwithmypi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='commands',
            name='ServerReply',
            field=models.ManyToManyField(to='resthackwithmypi.ServerReply'),
        ),
        migrations.AddField(
            model_name='commands',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 20, 19, 7, 48, 356286)),
        ),
        migrations.AddField(
            model_name='commands',
            name='UserShell',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='resthackwithmypi.UserShell'),
            preserve_default=False,
        ),
    ]
